# Generated by Django 5.0 on 2023-12-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_address_user_alter_cart_user_and_more'),
        ('users', '0002_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
